version: "3.7"

services:
  home-api:
    build: api/home/
    image: dadra-home-api
    ports:
      - "8080:3000"
    networks:
      - dadra-network
  write-api:
    build: api/write
    image: dadra-write-api
    ports:
      - "8081:3000"  
    networks:
      - dadra-network  

networks:
  dadra-network: {}